import { sendEmail } from '../utils/mailer.js';

// Franchise Application Controller
export const applyFrenchiseController = async (req, res) => {
  const { name, email, state, city, description } = req.body;
  if (!name || !email || !state || !city) {
    return res.status(400).json({ success: false, message: "name, email, state, and city are required." });
  }

  const subject = "🏢 New Franchise Application Request - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #eee; max-width: 600px; margin: auto;">
      <h2 style="color: #ff6600;">New Franchise Application</h2>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>State:</strong> ${state}</p>
      <p><strong>City:</strong> ${city}</p>
      <p><strong>Description:</strong> ${description || "<em>No description provided</em>"}</p>
      <hr style="margin: 20px 0;" />
      <p style="font-size: 0.9rem; color: #555;">This email was generated by the Grow Lotus Franchise form.</p>
    </div>
  `;

  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);

   sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};

// Private Funding Controller
export const privateFundingController = async (req, res) => {
  const { name, email, mobile, city, amount } = req.body;
  if (!name || !email || !mobile || !city || !amount) {
    return res.status(400).json({ success: false, message: "Missing required fields." });
  }

  const subject = "💼 New Private Funding Request - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="color: #ff6600;">Private Funding Details</h2>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Mobile:</strong> ${mobile}</p>
      <p><strong>City:</strong> ${city}</p>
      <p><strong>Amount:</strong> ${amount}</p>
    </div>
  `;

  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);
  sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};

// Enquiry Controller
export const enquiryController = async (req, res) => {
  const { name, phone, serviceType } = req.body;
  if (!name || !phone || !serviceType) {
    return res.status(400).json({ success: false, message: "name, phone, serviceType all are required fields." });
  }

  const subject = "📞 New Enquiry - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="color: #3366cc;">New Service Enquiry</h2>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Phone:</strong> ${phone}</p>
      <p><strong>Service Type:</strong> ${serviceType}</p>
    </div>
  `;

  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);
  sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};

// Finance Advice Controller
export const financeAdviceController = async (req, res) => {
  const { fullName, mobile, loanType } = req.body;
  if (!fullName || !mobile || !loanType) {
    return res.status(400).json({ success: false, message: "Missing required fields." });
  }

  const subject = "📋 Finance Advice Request - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="color: #009688;">Finance Advice Form</h2>
      <p><strong>Full Name:</strong> ${fullName}</p>
      <p><strong>Mobile:</strong> ${mobile}</p>
      <p><strong>Loan Type:</strong> ${loanType}</p>
    </div>
  `;

  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);
  sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};

// Contact Us Controller
export const contactUsController = async (req, res) => {
  const { name, email, mobile, message } = req.body;
  if (!name || !email || !mobile) {
    return res.status(400).json({ success: false, message: "Missing required fields." });
  }

  const subject = "📨 Contact Us Form - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="color: #673ab7;">New Contact Us Message</h2>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Mobile:</strong> ${mobile}</p>
      <p><strong>Message:</strong> ${message || "No message provided"}</p>
    </div>
  `;

  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);
  sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};


// Book a meeting Controller
export const BookAMeeting = async (req, res) => {
  const { name, email, mobile, message } = req.body;
  if (!name || !email || !mobile) {
    return res.status(400).json({ success: false, message: "Missing required fields." });
  }

  const subject = "📅 Book a Meeting Request - Grow Lotus";
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="color: #4CAF50;">New Meeting Request</h2>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Mobile:</strong> ${mobile}</p>
      <p><strong>Message:</strong> ${message || "No message provided"}</p>
      <hr style="margin-top: 20px;">
      <p style="font-size: 0.9rem; color: #555;">This request was submitted via the Book a Meeting form on Grow Lotus.</p>
    </div>
  `;
  // const result = await sendEmail({ subject, html });
  // return res.status(result.success ? 200 : 500).json(result);
  sendEmail({ subject, html }).catch(console.error);
   return res.status(200).json({ success: true, message: "Application received. We'll contact you soon." });
};
